name: rna_seq_viz
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - scikit-learn>=0.24.0
  - pip>=21.0
  - pip:
    - matplotlib-venn>=0.11.7
    - adjustText>=0.8
